### ISSUE TITLE
Doesn't work on  UIRemoteKeyboardWindow

### ISSUE THREAD

**Issue by anirudhamahale** [noursandid/SundeedSpotlight#2]
Library doesn't show anything if `UIApplication.shared.windows.last` is `UIRemoteKeyboardWindow`.
It works fine when I restart the application and if `UIApplication.shared.windows.last` is `UITextEffectsWindow`.

**Comment by noursandid** [comment]
I am checking it out right now, and it's working the first time but the second time I try to show the notification it's not showing,
the problem was setting in the ViewController

     static let sundeedWalkthrough = SundeedSpotlight() 

technically it shouldn't be static, and it was a mistake in my Example in the Readme file

please try and update me if you still have a problem with it

<img width="1405" alt="Screen Shot 2021-05-05 at 8 01 16 PM" src="https://user-images.githubusercontent.com/13000884/117180640-0cdb2c00-addd-11eb-9fed-88cdecadca78.png">
